apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/web
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: "web-port"
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
spec:
  backend:
    serviceName: web
    servicePort: 80
